### ISSUE TITLE
list adding a Long div at the end, causing a big space on bottom

### ISSUE THREAD

**Issue by sidwebworks** [aditya-kumawat/react-virtual-scroll#6]
Hi i am have been using this package in my chat app, it looks like as i add items to my list the component is creating a div on the bottom with a big height which causes spacing in my ui

**Comment by sidwebworks** [comment]
![image](https://user-images.githubusercontent.com/58144379/125199301-37d17880-e283-11eb-84cd-3a9d2f5bf47a.png)

**Comment by aditya-kumawat** [comment]
Can you please replicate the issue on codesandbox or share your code snippet over here?

**Comment by sidwebworks** [comment]
Sure btw also got this in console.
```Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at VirtualScroll.onScrollHandler (
```

**Comment by sidwebworks** [comment]
```jsx
// Modules
import React, { useCallback } from 'react';
import Message from './Message';
import VirtualScroll from 'react-dynamic-virtual-scroll';

const ListComponent = ({ messages }) => {
   console.log('messages: ', messages);

   const renderItem = useCallback(rowIndex => {
      const msg = messages[rowIndex];

      return (
         <Message
            userDp={msg.usrImg}
            username={msg.user?.split('#')[0]}
            message={msg.message.text}
            isRead={msg.read}
            isWelcome={msg.message?.first}
            key={msg.msgId}
            type={msg.type}
            senderId={msg.userId}
            msg={msg.msgId}
            timeStamp={msg.createdAt}
         />
      );
   }, []);

   return (
      <VirtualScroll
         className="List"
         minItemHeight={120}
         totalLength={messages.length}
         renderItem={renderItem}
      />
   );
};

export default ListComponent;

```

**Comment by sidwebworks** [comment]
is it possible to addEvent listeners on top and bottom of the component? for dynamic fetching?

**Comment by aditya-kumawat** [comment]
> is it possible to addEvent listeners on top and bottom of the component? for dynamic fetching?

No, it's not.
This library is meant for the purpose of partially rendering your rows even if you have thousands of rows of data with you.

**Comment by aditya-kumawat** [comment]
> ```js
> // Modules
> import React, { useCallback } from 'react';
> import Message from './Message';
> import VirtualScroll from 'react-dynamic-virtual-scroll';
> 
> const ListComponent = ({ messages }) => {
>    console.log('messages: ', messages);
> 
>    const renderItem = useCallback(rowIndex => {
>       const msg = messages[rowIndex];
> 
>       return (
>          <Message
>             userDp={msg.usrImg}
>             username={msg.user?.split('#')[0]}
>             message={msg.message.text}
>             isRead={msg.read}
>             isWelcome={msg.message?.first}
>             key={msg.msgId}
>             type={msg.type}
>             senderId={msg.userId}
>             msg={msg.msgId}
>             timeStamp={msg.createdAt}
>          />
>       );
>    }, []);
> 
>    return (
>       <VirtualScroll
>          className="List"
>          minItemHeight={120}
>          totalLength={messages.length}
>          renderItem={renderItem}
>       />
>    );
> };
> 
> export default ListComponent;
> ```

Most likely, your `Message` component doesn't accept `className` prop. Either add support for `className` or add `VS-item` class in your `Message` component.

**Comment by sidwebworks** [comment]
alright thanks a lot brother i will try this, but yeh do u know why this is coming
```
index.js:1 Warning: React does not recognize the `renderItem` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `renderitem` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by aditya-kumawat** [comment]
This is a known warning. You can ignore this for now. It won't break anything, nor will affect your performance.
Will fix it in the new release.

**Comment by sidwebworks** [comment]
Okay although issue seems to persist, after adding the VS-item class also, after approximately 50 items the huge bottom div comes back

**Comment by sidwebworks** [comment]
Also for some information, i have a Infinite scroll component as the parent element as when i scroll to top it fetches and adds new items to my array, it works fine but after 50 items or so the List brings in a huge div

**Comment by aditya-kumawat** [comment]
This library is not suitable for use when you are loading data in chunks on top of it.
