### ISSUE TITLE
Error to use renderItem

### ISSUE THREAD

**Issue by dannpl** [aditya-kumawat/react-virtual-scroll#7]
`renderItem` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `renderitem` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

```
package.json
...
"react": "17.0.2",
"react-dom": "17.0.2",
```

**Comment by nadine-belanova** [comment]
Hi, I have the same issue
`"react-dynamic-virtual-scroll": "^1.3.2"`
Any update on this?
Thanks

**Comment by aditya-kumawat** [comment]
I need to check. Will fix it by end of this week.

**Comment by nadine-belanova** [comment]
It would be really great. I like your virtual scroll very much. If it helps, you can see this error in the console in your example - [https://codesandbox.io/s/virtual-scroll-simple-list-27om6](https://codesandbox.io/s/virtual-scroll-simple-list-27om6)

**Comment by nadine-belanova** [comment]
Hi, any news?

**Comment by aditya-kumawat** [comment]
Oh, I totally forgot about it since I was running a little busy recently. My bad.
Released a version(v1.3.3) for the fix.

**Comment by aditya-kumawat** [comment]
Released a minor(v1.4.0) instead. Will unpublish the released patch.

**Comment by nadine-belanova** [comment]
Thanks a lot for taking the time to do this.
